server:
  port: 8082

logging:
  level:
    org.springframework: INFO

spring:
  messages:
    basename: message

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: metawater
    password: 1234

  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.metawater
#  type-aliases-package: com.example.metajobs

#metawater.upload.path : C:\\upload
metawater.upload.path : C:\metanet\workspace\finalProject\MetaFinalProject\src\main\resources\files

