server:
  port: 8082

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: message

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: metawater
    password: 1234

  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.metawater
#  type-aliases-package: com.example.metajobs

